# Generated by Django 3.0.7 on 2020-07-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Reading', 'Reading'), ('To_Read', 'To Read')], default='', max_length=10),
        ),
    ]
