# Generated by Django 3.0.7 on 2020-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_belonging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('To_Read', 'To Read'), ('Reading', 'Reading')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Belonging',
        ),
    ]
