# Generated by Django 3.0.7 on 2020-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200728_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('To_Read', 'To Read'), ('Reading', 'Reading'), ('Read', 'Read')], default='', max_length=10),
        ),
    ]
