# Generated by Django 3.0.7 on 2020-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200728_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('To_Read', 'To Read'), ('Read', 'Read'), ('Reading', 'Reading')], default='', max_length=10),
        ),
    ]
